spring:
  application:
    name: componente-b

server:
  port: 8082

# Configuración de Feign Client
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic

# URL del Componente A
componente-a:
  url: http://localhost:8081

# Configuración OpenAPI
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
